#! /bin/sh

bspc monitor -d I II III IV V

bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}

desktop_config border_width	2
desktop_config window_gap	24

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config auto_alternate	true
bspc config auto_cancel	true

#bspc config normal_border_color "#cccccc"
#bspc config focused_border_color "#333333"
#bspc config presel_border_color "#cc6666"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0

# run panel
workspaces
