#!bin/sh

# annoying
alias quit='exit'
alias :q='quit'
alias please='sudo `fc -n -l -1`'
alias svim='sudoedit'

# protection
alias rm='rm -I'
alias cp='cp -vi'
alias mv='mv -i'

# colour
alias grep='grep --color=auto'
alias ls='ls -h --color=auto'
alias l='ls -CF --color=auto'
alias ll='ls -alhF --color=auto'

# pacman
alias pacman='sudo pacman'
alias paupg='sudo pacupg'

# short
alias vi='vim'
alias c='xsel -ib'
alias ch='sudo chmod 755'
alias tp='trash-put'
alias tl='trash-list'

