#!/bin/sh
# einvornment variables

# programs
export BROWSER="firefox"
export EDITOR="vim"
export VISUAL="$EDITOR"
export SXHKD_SHELL="/bin/sh"
export SYSTEMD_PAGER="less -j4aR"
export GPG_TTY=$(tty)
export GPGKEY="D40CEBED"
export PASSWORD_STORE_DIR="$HOME/usr/sync/pass"

# disabled until I figure out how to resolve conflict with git diff colors
#export LESS="FX"

# language
export LC_ALL=
export LC_COLLATE="C"

# tmp
export TMPDIR="/tmp/$USER"

# gpg-agent ssh
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
	export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
fi

# default dirs
[[ $XDG_CONFIG_HOME ]] || export XDG_CONFIG_HOME="$HOME/.config"

# set path
path=($HOME/bin)
case ":$PATH:" in
	*":$path:"*) :;; # already there
	*) PATH="$path:$PATH";;
esac
